### PR TITLE
[irods/irods#7312] Get package revision from IrodsCPackCommon

### PR DESCRIPTION
**Pull request by SwooshyCueb**

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Please notify when this is out of draft. Thanks

**Review by korydraughn — APPROVED** [review]
Looks good to me.

Let's wait for one more approval before adding the pound.

**Review by alanking — APPROVED** [review]
Yep, # it.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
