### PR TITLE
[#51] Added support for escaping single quotes (4-2-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
Cherry-picked from #57.

### CODE REVIEW

**Review by alanking — APPROVED** [review]
\# it

**Comment by korydraughn** [comment]
#'d

**Comment by korydraughn** [comment]
Hold on merging this.

**Comment by korydraughn** [comment]
I'm seeing different behavior on Ubuntu 18 / PostgreSQL 10 for some reason.

**Comment by korydraughn** [comment]
Perhaps I'm not seeing different behavior since the string I'm searching for includes an exclamation mark.

This string, `[]{}()#!%`, is only returned if I run the following:
```
echo -e "select DATA_NAME where DATA_NAME = '[]{}()#\x21%'" | iquery | jq
```

I think this also applies to the main branch. I just didn't see it because the string I was testing against included a backslash before the exclamation mark.

With that said, we can at least have a workaround thanks to the pipe syntax.

I'm going to link this comment in a new issue so we don't forget to revisit it.

**Comment by korydraughn** [comment]
Also, I had to add libboost_system.so to the list of things to link against on Ub18 for some reason. It's not clear to me why that was necessary this time.

Regardless, it compiles now.

Merging.

**Pull request merged**
