### PR TITLE
[irods/irods#6251,irods/irods#6256] find_package for fmt and spdlog

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#6251
In service of irods/irods#6256

Ignore the branch name.

Once this is merged, a 4-3-stable branch should be created.

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
> For my own understanding, we don't need to specify `spdlog::spdlog_header_only` here because it is linked as "public" in the `irods_common` library, right?

That's correct.

If we were actually using spdlog directly in this project, we would want to anyway, though.

**Review by korydraughn — APPROVED** [review]
Looks good to me.

Pound when ready.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by alanking** [comment]
Created 4-3-stable branch based on https://github.com/irods/irods_api_plugin_genquery2/pull/88/commits/ae166d0f8705b79bf7b6bc4072c463a5eadef3ba

**Pull request merged**
